namespace EMRNext.Core.Stubs {
    public interface IEmailService {}
    public interface ISMSService {}
    public interface IPushNotificationService {}
    public interface IMessageBroker {}
    public interface IPreferenceService {}
    public interface ILabOrderService {}
    public interface IImagingService {}
    public interface IDocumentStorageService {}
    public interface ISecurityService {}
    public interface IUserContext {}
    public interface ITaskValidator {}
    public interface IAuditService {}
    public interface IAlertService {}
    public interface INotificationService {}
    public interface IEncryptionService {}
    public interface IPrescriptionRepository {}
    public interface IDrugInteractionRepository {}
    public interface IPatientRepository {}
    public interface IVitalSignRepository {}
    public interface IAuditRepository {}
    public interface IGrowthDataRepository {}
    public interface ISchedulingService {}
    public interface IBillingService {}
    public interface IDocumentService {}
    public interface ILabInterfaceEngine {}
    public interface IEMRIntegrationService {}
    public interface IDICOMService {}
    public interface IPortalService {}
    public interface IPortalAuthenticationService {}

    public class Result {}
    public class Alert {}
    public class Recommendation {}
    public class TimeSlot {}
    public class WaitlistEntry {}
    public class ScheduleMetrics {}
    public class UtilizationReport {}
    public class WorkQueueTask {}
    public class WorkQueueTaskRequest {}
    public class TaskPriority {}
    public class NotificationPriority {}
    public class PreAuthorizationResult {}
    public class PreAuthRequest {}
    public class InsuranceEligibility {}
    public class Statement {}
    public class Account {}
    public class AccountBalance {}
    public class FeeSchedule {}
    public class Adjustment {}
    public class CreditCheck {}
    public class PaymentPlan {}
    public class LabOrderReport {}
    public class LabResultReport {}
    public class LabOrderSummary {}
    public class InterfaceError {}
    public class QualityReport {}
    public class QualityIssue {}
    public class AlertRequest {}
    public class DocumentRequest {}
    public class PortalUserDevice {}
}
